### ISSUE TITLE
Plugin not work in Webstorm & Goland

### ISSUE THREAD

**Issue by tuluffy** [ice1000/zig-intellij#45]
**Error Info:**
<img width="814" alt="image" src="https://user-images.githubusercontent.com/26808339/203463207-0353827a-65ee-49c7-95a3-dba737348534.png">
```
java.lang.NoClassDefFoundError: org/eclipse/egit/github/core/client/GitHubClient
	at org.ziglang.error.AnonymousFeedback.sendFeedback(error-report.kt:95)
	at org.ziglang.error.AnonymousFeedbackTask.run(error-report.kt:271)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: org.eclipse.egit.github.core.client.GitHubClient PluginClassLoader(plugin=PluginDescriptor(name=Zig, id=org.ziglang, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/WebStorm2022.2/plugins/intellij-zig, version=0.1.4, package=null, isBundled=false), packagePrefix=null, instanceId=1, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:214)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 22 more
```

**Version:**
- zig-plugin
<img width="405" alt="image" src="https://user-images.githubusercontent.com/26808339/203463438-c03d113d-0cac-44f5-8263-7943ec795700.png">

- webstrom
<img width="416" alt="image" src="https://user-images.githubusercontent.com/26808339/203463373-136fb436-b373-4686-9e0b-9983a0644c5c.png">

**Comment by ice1000** [comment]
But why
